-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Kilpailija CASCADE;
DROP TABLE IF EXISTS Ranking_pisteet CASCADE;
DROP TABLE IF EXISTS Kilpailu CASCADE;
DROP TABLE IF EXISTS Sarjan_osallistuja CASCADE;
DROP TABLE IF EXISTS Kilpailun_sarja CASCADE;
